fix(electron): Add missing `tslib` dependency
By manually packaging the application I've had the following issue when running the application:

```
Error: Cannot find module 'tslib'
```

The runtime depends on it because we enable `importHelpers` in `tsconfig.json`.
The fix for that error is simple: Make the package depends directly on `tslib` for it to be included in `app.asar`.