fix(build): Install rust with toolchain (#9854)
Installing rustup without a specific toolchain was failing when using
`cargo` directly:

```shell
$ cargo --version
error: toolchain '1.81.0-x86_64-unknown-linux-gnu' is not installed
help: run `rustup toolchain install 1.81.0-x86_64-unknown-linux-gnu` to install it
```

This is likely due to `rustup-1.28` that no longer automatically install
the active toolchain.