fix(client_connection): Enable HTTP/2 support
During testing of `parsec-cli` we encountered the following panic `invite claim <url>` command:

```
thread 'main' (126900) panicked at /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hyper-util-0.1.13/src/client/legacy/client.rs:577:33:
http2 feature is not enabled
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <core::pin::Pin<P> as core::future::future::Future>::poll
   3: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
   4: <hyper_util::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
   5: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   6: hyper_util::client::legacy::client::Client<C,B>::send_request::{{closure}}
   7: <hyper_util::client::legacy::client::ResponseFuture as core::future::future::Future>::poll
   8: <reqwest::async_impl::client::HyperService as tower_service::Service<http::request::Request<reqwest::async_impl::body::Body>>>::call::{{closure}}
   9: <tower::retry::future::ResponseFuture<P,S,Request> as core::future::future::Future>::poll
  10: <tower_http::follow_redirect::ResponseFuture<S,ReqBody,P> as core::future::future::Future>::poll
  11: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
  12: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
  13: libparsec_client_connection::invited_cmds::InvitedCmds::internal_send::{{closure}}
  14: parsec_cli::commands::invite::claim::main::{{closure}}
  15: parsec_cli::commands::invite::dispatch_command::{{closure}}
  16: parsec_cli::main::{{closure}}
  17: tokio::runtime::park::CachedParkThread::block_on
  18: tokio::runtime::context::runtime::enter_runtime
  19: tokio::runtime::runtime::Runtime::block_on
  20: parsec_cli::main
```

The error stack point to `libparsec_client_connection::invited_cmds::InvitedCmds::internal_send` which then use `reqwest` to send the HTTP reqwest.

The panic error message is clear about what missing (the `http2` feature) and where to add it (enable the `http2` feature for reqwest)